action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,16 +10,6 @@ inputs:
   key:
     description: 'An explicit key for restoring and saving the cache'
     required: true
-  restore-keys:
-    description: 'An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.'
-    required: false
-  upload-chunk-size:
-    description: 'The chunk size used to split up large files during upload, in bytes'
-    required: false
-  enableCrossOsArchive:
-    description: 'An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms'
-    default: 'false'
-    required: false
   fail-on-cache-miss:
     description: 'Fail the workflow if cache entry is not found'
     default: 'false'
@@ -31,8 +21,10 @@ inputs:
 outputs:
   cache-hit:
     description: 'A boolean value to indicate an exact match was found for the primary key'
+    value: ${{ steps.check-cache.outputs.cache-hit }}
 runs:
     using: 'composite'
+
     steps:
       - name: Check Runner OS
         if: ${{ runner.os != 'Linux' }}
@@ -40,4 +32,33 @@ runs:
         run: |
           echo "::error title=⛔ error hint::Support Linux Only"
           exit 1
-          
+
+      #check if cache exists
+      - name: Setup env
+        shell: bash
+        run: |
+          echo "CACHE_PATH=$GITHUB_WORKSPACE/../_cache/${{ inputs.key }}" >> $GITHUB_ENV
+
+      - name: Check if cache exists
+        shell: bash
+        id: check-cache
+        run: |
+          ls -lah $CACHE_PATH && echo "cache-hit=true" >> $GITHUB_OUTPUT || true
+
+      - if: ${{ inputs.fail-on-cache-miss && steps.check-cache.outputs.cache-hit != 'true' }}
+        name: Fail on cache miss
+        shell: bash
+        run: |
+          echo "::error title=⛔ error hint::Cache not found"
+          exit 1
+
+      - if: ${{ inputs.lookup-only != 'true' }}
+        uses: pyTooling/Actions/with-post-step@v0.4.5
+        name: Restore cache
+        with:
+          main: |
+            # restore cache
+            ls $CACHE_PATH && cpio -i -vd < $CACHE_PATH || echo "No cache to restore."
+          post: |
+            # save cache
+            find ${{inputs.path}} -print -depth | cpio -o -v > $CACHE_PATH
